### ISSUE TITLE
Lack of progress

### ISSUE THREAD

**Issue by Adman** [RoboCupJuniorTC/rcj-soccer-sim#11]
If the ball does not change its position within some timespan, move the ball to the nearest unoccupied neutral spot.

**Comment by mrshu** [comment]
@Adman to put this together by the specification, #21 needs to be augmented with (at least) the positions of the neutral spots. Plus we ought to have some way of checking whether the neutral spot is occupied or not.

**Comment by felipenmartins** [comment]
I guess this one is solved, right?

**Comment by mrshu** [comment]
@felipenmartins partially -- we still don't have the "find the nearest neutral spot" part figured out but I guess we can close this already and create a new issue to track the progress of this feature.
