### ISSUE TITLE
Fix temporary workaround for setting ball's velocity to zero

### ISSUE THREAD

**Issue by Adman** [RoboCupJuniorTC/rcj-soccer-sim#92]

**Comment by mrshu** [comment]
@Adman This has been fixed already, right?

**Comment by Adman** [comment]
@mrshu Webots created some fix but the problem still persists there.
